### PR TITLE
UPDATE ENTITY PLEASE

### PR DESCRIPTION
**Pull request by amrcstake**
THIS IS OUR PULL REQUEST

### CODE REVIEW

**Comment by amrcstake** [comment]
WAITING

**Review by amrcstake — COMMENTED** [review]
WAITNG

**Comment by kostko** [comment]
The signed metadata statement should only be in the `registry/entity` directory, but you also have one at the root. Please remove the one that exists at the root.

**Comment by amrcstake** [comment]
> The signed metadata statement should only be in the `registry/entity` directory, but you also have one at the root. Please remove the one that exists at the root.

its done was removed

**Comment by kostko** [comment]
It's still there, see here: https://github.com/oasisprotocol/metadata-registry/pull/166/files#diff-ce54fb46750111735a8e7b82f85b7584fca82917f4e4d6593f2a9127a15f6110

**Comment by amrcstake** [comment]
> It's still there, see here: https://github.com/oasisprotocol/metadata-registry/pull/166/files#diff-ce54fb46750111735a8e7b82f85b7584fca82917f4e4d6593f2a9127a15f6110

please check again

**Comment by kostko** [comment]
Now you removed the wrong one.

**Comment by amrcstake** [comment]
> Now you removed the wrong one.

i put again

**Comment by kostko** [comment]
It is still in the wrong place, as I said above it must be under `registry/entity` together with all of the existing statements.

**Comment by amrcstake** [comment]
> It is still in the wrong place, as I said above it must be under `registry/entity` together with all of the existing statements.

this is the complete path 
/home/trifasicko/metadata-registry/registry/entity/da599caaa5f01b37a37ba8c6a2c209ac32807beac95e7f5770f705edecec258c.json

**Comment by kostko** [comment]
You can browse your repository here to see where the file is currently: https://github.com/amrcstake/metadata-registry

**Review by kostko — APPROVED** [review]

**Comment by amrcstake** [comment]
> You can browse your repository here to see where the file is currently: https://github.com/amrcstake/metadata-registry

thank you

**Pull request merged**
