### PR TITLE
 update metadata for MIT Digital Currency Group entity BhVn8vaynXJqNe…

### PR DESCRIPTION
**Pull request by kobrien**
…qwE26N5HeqtvxlbrozavGT26sG5ik=

### CODE REVIEW

**Comment by kobrien** [comment]
looks like the file wasn't already present in the repo, why this is I dont know, but i suspect i should not have given it a serial number of 2 in this case? going to close this MR, and redo it from a fresh branch

**Comment by kobrien** [comment]
on closer inspection, the file does exist

registry/entity/061567f2f6b29d726a35eab0136e8de477aab6fc656eba336af193dbab06e629.json

however the public key does not look correct? 
`public_key":"git p="`

**Comment by kostko** [comment]
The problem is that the branch is out of date, can you rebase it on top of the latest production branch?

**Comment by kostko** [comment]
> looks like the file wasn't already present in the repo, why this is I dont know

When did you submit it?

> on closer inspection, the file does exist
> 
> registry/entity/061567f2f6b29d726a35eab0136e8de477aab6fc656eba336af193dbab06e629.json
> 
> however the public key does not look correct?
> `public_key":"git p="`

Where did you find this? I don't see it in the current production repository:
https://github.com/oasisprotocol/metadata-registry/tree/caff35cea152792b52db16f0e9eaae540a239f95/registry/entity

**Comment by kobrien** [comment]
2nd PR merged, closing this now, not sure what happened with the pub key stuff above must have been a bad merge on my part... Thanks @kostko !

**Pull request closed without merging**
