### PR TITLE
add blockscape testnode validator

### PR DESCRIPTION
**Pull request by MarcelMWS**
set entity-metadata.json description

### CODE REVIEW

**Review by kostko — CHANGES_REQUESTED** [review]
Why are you trying to merge into the `testing` branch? That one is only used for testing the metadata registry implementations.

**Comment by MarcelMWS** [comment]
ah okay, I thought this was for testnet. where is the repo to register a validator info/description for the oasis testnet?

**Comment by kostko** [comment]
You should use the same `production` branch even for testnet.

**Comment by MarcelMWS** [comment]
okay we can close this. I prepare a new pr :)

**Pull request closed without merging**
